[package]
name = "async-net-server-utils"
version = "0.1.0"
edition = "2018"

[dependencies]
async-tungstenite = "0.15.0"
async-net = "1.6.1"
async-io = "1.6.0"
async-rustls = "0.2.0"
log = "0.4.14"
rustls-acme = "0.2.0"
futures-util = "0.3.17"
futures-lite = "1.12.0"
httparse = "1.5.1"
anyhow = "1.0.44"
http = "0.2.5"
pin-project = "1.0.8"